export default {

	SEARCH_PODCASTS: 'SEARCH_PODCASTS',
	PODCASTS_RECEIVED: 'PODCASTS_RECEIVED',
	PODCAST_SELECTED: 'PODCAST_SELECTED',
	TRACKLIST_READY: 'TRACKLIST_READY',

	// Test
	PODCASTS_TEST: 'PODCASTS_TEST'
}